// Copyright 2026 QMK Collaborators
// SPDX-License-Identifier: MIT

using System.Text;
using Xap.SourceGenerator.Helpers;
using Xap.SourceGenerator.Models;

namespace Xap.SourceGenerator.Generators;

/// <summary>
/// Emits <c>Xap.Broadcasts.g.cs</c>: the (non-<c>[Flags]</c>) <c>XapBroadcast</c> enum plus a
/// partial <c>XapClient</c> piece with one event per broadcast message and the dispatch switch
/// that raises them. Only invoked by XapSpecGenerator when the spec declares
/// <c>broadcast_messages</c> -- <c>XapClientBase.HandleIncoming</c> (Xap.Core) always calls
/// the virtual <c>OnBroadcastReceived</c> hook this file overrides, and when this generator
/// doesn't run at all (no broadcast_messages), the base class's own no-op override handles it,
/// so a spec with none still compiles and simply drops token 0xFFFF frames.
/// </summary>
internal static class BroadcastGenerator
{
    public static string GenerateBroadcasts(BroadcastMessagesModel model)
    {
        var messages = model.Messages.Values.ToList();
        bool hasSecureStatus = messages.Any(m => m.Define == "SECURE_STATUS");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Xap;");
        sb.AppendLine();

        sb.AppendLine("public enum XapBroadcast : byte");
        sb.AppendLine("{");
        foreach (BroadcastMessage? msg in messages)
            sb.AppendLine($"    {CSharpNaming.ToClassName(msg.Define)} = {CSharpNaming.ParseHexByte(msg.Id)},");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("public sealed partial class XapClient");
        sb.AppendLine("{");

        foreach (BroadcastMessage? msg in messages)
            sb.AppendLine($"    public event {EventDelegateType(msg)}? {EventName(msg)};");
        sb.AppendLine();

        // OnBroadcastReceived runs synchronously on the receive loop; SECURE_STATUS is reconciled
        // here (not in DispatchBroadcastAsync) to preserve wire order.
        sb.AppendLine("    protected override void OnBroadcastReceived(RawMessage message)");
        sb.AppendLine("    {");
        if (hasSecureStatus)
        {
            sb.AppendLine("        // span[3] >= 1: never read a padding byte past the declared payload as a status");
            sb.AppendLine("        // (real HID reports are a fixed 64 bytes, so trailing padding always exists).");
            sb.AppendLine("        var span = message.Data.Span;");
            sb.AppendLine("        if (span.Length >= 5 && span[2] == (byte)XapBroadcast.SecureStatus && span[3] >= 1)");
            sb.AppendLine("            SetSecureUnlocked(span[4] == 0x02);");
        }
        sb.AppendLine("        _ = DispatchBroadcastAsync(message);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Parses a broadcast frame as token(2 LE, always 0xFFFF) + type(1) + length(1) +");
        sb.AppendLine("    /// payload, then dispatches by <see cref=\"XapBroadcast\"/>. Fire-and-forget from");
        sb.AppendLine("    /// HandleIncoming (never awaited on the receive loop itself): awaiting a broadcast");
        sb.AppendLine("    /// handler there could deadlock if the handler issues its own command and waits on");
        sb.AppendLine("    /// the very receive loop it is blocking.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private async Task DispatchBroadcastAsync(RawMessage msg)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var data = msg.Data;");
        sb.AppendLine("            if (data.Length < 4)");
        sb.AppendLine("                throw new XapParseException($\"Broadcast frame needs at least 4 bytes, got {data.Length}.\");");
        sb.AppendLine("            byte type = data.Span[2];");
        sb.AppendLine("            byte length = data.Span[3];");
        sb.AppendLine("            if (data.Length < 4 + length)");
        sb.AppendLine("                throw new XapParseException($\"Broadcast 0x{type:X2} declares {length} payload byte(s) but only {data.Length - 4} are present.\");");
        sb.AppendLine("            var payload = data.Slice(4, length);");
        sb.AppendLine();
        sb.AppendLine("            switch ((XapBroadcast)type)");
        sb.AppendLine("            {");
        foreach (BroadcastMessage? msg in messages)
            AppendCase(sb, msg);
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            OnBroadcastError(ex);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    // ---- Per-message event/case shape --------------------------------------------------------

    private static string EventName(BroadcastMessage msg) => msg.Define switch
    {
        "LOG_MESSAGE" => "LogMessageReceived",
        "SECURE_STATUS" => "SecureStatusChanged",
        _ => CSharpNaming.ToClassName(msg.Define) + "Received",
    };

    private static string EventDelegateType(BroadcastMessage msg) => msg.Define switch
    {
        "SECURE_STATUS" => "System.Func<XapSecureStatus, Task>",
        _ => "System.Func<System.ReadOnlyMemory<byte>, Task>",
    };

    private static void AppendCase(StringBuilder sb, BroadcastMessage msg)
    {
        // Each case gets its own braced block scope: pattern variables would otherwise collide
        // across sibling case labels, which all share one switch-statement scope.
        sb.AppendLine($"                case XapBroadcast.{CSharpNaming.ToClassName(msg.Define)}:");
        sb.AppendLine("                {");
        switch (msg.Define)
        {
            case "LOG_MESSAGE":
                sb.AppendLine("                    await AwaitAllAsync(LogMessageReceived, payload);");
                sb.AppendLine("                    break;");
                break;
            case "SECURE_STATUS":
                sb.AppendLine("                    if (payload.Length < 1)");
                sb.AppendLine("                        throw new XapParseException(\"SECURE_STATUS broadcast payload must be at least 1 byte.\");");
                sb.AppendLine("                    var status = (XapSecureStatus)payload.Span[0];");
                sb.AppendLine("                    await AwaitAllAsync(SecureStatusChanged, status);");
                sb.AppendLine("                    break;");
                break;
            default:
                sb.AppendLine($"                    await AwaitAllAsync({EventName(msg)}, payload);");
                sb.AppendLine("                    break;");
                break;
        }
        sb.AppendLine("                }");
    }

}
