// Copyright 2026 QMK Collaborators
// SPDX-License-Identifier: MIT

using System.Globalization;
using System.Text;
using Xap.SourceGenerator.Helpers;
using Xap.SourceGenerator.Models;

namespace Xap.SourceGenerator.Generators;

/// <summary>
/// Emits <c>Xap.XapClient.g.cs</c>: the generated <c>XapClient : XapClientBase</c> partial (one
/// generated subsystem class per router, top-level and nested, walked recursively so arbitrary
/// nesting depth works without per-subsystem special-casing), <c>CreateAsync</c>/
/// <c>InitializeCapabilitiesAsync</c>, per-route command methods, capability (<c>Has*</c>)
/// gating, and the secure-route pre-send guard. Everything spec-invariant (transport wiring,
/// token allocation, request framing, receive-loop correlation, <c>ExecuteAsync</c>, lifecycle)
/// lives in the hand-written <c>Xap.Core.XapClientBase</c> instead.
/// </summary>
internal static class ClientGenerator
{
    private sealed class SubsystemInfo
    {
        public string ClassName = "";
        public string PropertyName = "";
        public bool HasCapabilities;
        public RouteNode Node = null!;
    }

    public static string GenerateClient(XapSpecModel model)
    {
        bool hasGetSecureStatus = HasRoute(model.Routes, "GET_SECURE_STATUS");

        var subsystemsSb = new StringBuilder();
        var topLevel = new List<SubsystemInfo>();
        foreach (RouteNode node in model.Routes.Values)
            topLevel.Add(BuildSubsystemTree(node, [], [], subsystemsSb));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Buffers.Binary;");
        sb.AppendLine();
        sb.AppendLine("namespace Xap;");
        sb.AppendLine();
        // XapClientBase (Xap.Core) holds every spec-invariant piece: transport wiring,
        // token allocation, request framing, receive-loop correlation, and lifecycle. Only the
        // genuinely spec-dependent surface is generated here: the subsystem property tree and
        // CreateAsync/InitializeCapabilitiesAsync (which needs the actual route bytes).
        sb.AppendLine("public sealed partial class XapClient : XapClientBase");
        sb.AppendLine("{");

        foreach (SubsystemInfo info in topLevel)
            sb.AppendLine($"    public {info.ClassName} {info.PropertyName} {{ get; }}");
        if (topLevel.Count > 0)
            sb.AppendLine();

        sb.AppendLine("    public XapClient(IXapTransport transport) : base(transport)");
        sb.AppendLine("    {");
        foreach (SubsystemInfo info in topLevel)
            sb.AppendLine($"        {info.PropertyName} = new {info.ClassName}(this);");
        sb.AppendLine("    }");
        sb.AppendLine();

        if (hasGetSecureStatus)
            AppendSecureStatusTracking(sb);

        AppendCreateAsync(sb, topLevel);

        sb.AppendLine("}");
        sb.AppendLine();
        sb.Append(subsystemsSb);

        return sb.ToString();
    }
    // ---- CreateAsync / InitializeCapabilitiesAsync -----------------------------------------

    /// <summary>
    /// Emits the CreateAsync factory and its InitializeCapabilitiesAsync helper. XAP itself is
    /// special-cased here (and only here) because it is the one subsystem that is always
    /// initialized unconditionally and is the sole source of the enabled-subsystem bitmask
    /// (SUBSYSTEM_QUERY, XAP route 0x00,0x02 in the real spec -- located generically below by
    /// define name, not hardcoded, though the route table is authoritative over any mislabeled
    /// prose elsewhere in the spec JSON). Every other top-level subsystem is gated generically:
    /// if it has its own CAPABILITIES_QUERY route, it is initialized iff the corresponding bit
    /// (indexed by ITS OWN route id, via the XapConstants.Route&lt;X&gt; constant ConstantsGenerator
    /// emits) is set in the enabled bitmask. Subsystems without a capabilities route (KB/USER)
    /// are skipped entirely, since they have zero children.
    /// </summary>
    private static void AppendCreateAsync(StringBuilder sb, List<SubsystemInfo> topLevel)
    {
        SubsystemInfo? xapInfo = topLevel.FirstOrDefault(i => i.Node.Define == "XAP");
        if (xapInfo is null)
        {
            // No XAP subsystem in this spec (should not happen for a real XAP spec) -- emit a
            // CreateAsync that just constructs the client with no capability discovery, rather
            // than crashing the generator on an edge-case/malformed spec.
            sb.AppendLine("    public static async Task<XapClient> CreateAsync(IXapTransport transport, CancellationToken ct = default)");
            sb.AppendLine("    {");
            sb.AppendLine("        await Task.CompletedTask.ConfigureAwait(false);");
            sb.AppendLine("        return new XapClient(transport);");
            sb.AppendLine("    }");
            sb.AppendLine();
            return;
        }

        RouteNode? subsystemQueryNode = xapInfo.Node.Routes.Values
            .FirstOrDefault(c => !c.IsRouter && c.Define == "SUBSYSTEM_QUERY");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates and initializes an XapClient: initializes the always-present XAP");
        sb.AppendLine("    /// subsystem, queries the enabled-subsystem bitmask, and initializes every other");
        sb.AppendLine("    /// top-level subsystem that is both capability-bearing and reported enabled.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static async Task<XapClient> CreateAsync(IXapTransport transport, CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var client = new XapClient(transport);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            await client.InitializeCapabilitiesAsync(ct).ConfigureAwait(false);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch");
        sb.AppendLine("        {");
        sb.AppendLine("            await client.DisposeAsync().ConfigureAwait(false);");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("        return client;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private async Task InitializeCapabilitiesAsync(CancellationToken ct)");
        sb.AppendLine("    {");

        if (xapInfo.HasCapabilities)
            sb.AppendLine($"        await {xapInfo.PropertyName}.InitializeAsync(ct).ConfigureAwait(false);");

        if (subsystemQueryNode is not null)
        {
            string routeBytes = FormatByteArrayLiteral([CSharpNaming.ParseHexByte(xapInfo.Node.Id), CSharpNaming.ParseHexByte(subsystemQueryNode.Id)]);
            sb.AppendLine();
            sb.AppendLine("        var token = AllocateToken();");
            sb.AppendLine($"        var frame = BuildRequest(token, {routeBytes});");
            sb.AppendLine("        uint enabled = await ExecuteAsync<uint>(token, frame, XapReaders.U32, ct).ConfigureAwait(false);");
            sb.AppendLine();

            foreach (SubsystemInfo info in topLevel)
            {
                if (ReferenceEquals(info, xapInfo) || !info.HasCapabilities)
                    continue;
                sb.AppendLine($"        if ((enabled & (1u << XapConstants.Route{CSharpNaming.ToClassName(info.Node.Define)})) != 0)");
                sb.AppendLine($"            await {info.PropertyName}.InitializeAsync(ct).ConfigureAwait(false);");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ---- Secure-state cache reconciliation (GET_SECURE_STATUS) -----------------------------

    /// <summary>
    /// Emits the bookkeeping that lets the secure-state cache be reconciled synchronously on the
    /// receive loop (via OnResponseCorrelated) rather than in GetSecureStatusAsync's continuation.
    /// </summary>
    private static void AppendSecureStatusTracking(StringBuilder sb)
    {
        sb.AppendLine("    private readonly System.Collections.Concurrent.ConcurrentDictionary<ushort, byte> _secureStatusTokens = new();");
        sb.AppendLine();
        sb.AppendLine("    internal void WatchSecureStatusResponse(ushort token)");
        sb.AppendLine("        => _secureStatusTokens.TryAdd(token, 0);");
        sb.AppendLine();
        sb.AppendLine("    // A watch entry must not outlive its request: tokens recycle, so a stale entry");
        sb.AppendLine("    // would misread a later, unrelated response as a secure status.");
        sb.AppendLine("    internal void UnwatchSecureStatusResponse(ushort token)");
        sb.AppendLine("        => _secureStatusTokens.TryRemove(token, out _);");
        sb.AppendLine();
        sb.AppendLine("    protected override void OnResponseCorrelated(ushort token, RawMessage message)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_secureStatusTokens.TryRemove(token, out _))");
        sb.AppendLine("            return;");
        sb.AppendLine();
        sb.AppendLine("        // span[3] >= 1: never read a padding byte past the declared payload as a status");
        sb.AppendLine("        // (real HID reports are a fixed 64 bytes, so trailing padding always exists).");
        sb.AppendLine("        System.ReadOnlySpan<byte> span = message.Data.Span;");
        sb.AppendLine("        if (span.Length >= 5 && span[3] >= 1 && ((ResponseFlags)span[2] & ResponseFlags.Success) != 0)");
        sb.AppendLine("            SetSecureUnlocked(span[4] == 2);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>Recursively searches the route tree for a leaf (non-router) route with the given Define.</summary>
    private static bool HasRoute(Dictionary<string, RouteNode> routes, string define)
    {
        foreach (RouteNode node in routes.Values)
        {
            if (!node.IsRouter)
            {
                if (node.Define == define)
                    return true;
            }
            else if (HasRoute(node.Routes, define))
            {
                return true;
            }
        }
        return false;
    }

    // ---- Subsystem tree walk ----------------------------------------------------------------

    /// <summary>
    /// Recursively emits one subsystem class for <paramref name="node"/> (a router -- top-level
    /// or nested) and all of its router descendants, appending each class's source to
    /// <paramref name="output"/>. This is the single generic algorithm behind every subsystem
    /// class in the tree: no per-subsystem-name special-casing, so it scales to whatever nesting
    /// depth a spec declares.
    /// </summary>
    /// <param name="ancestorDefines">Router Defines from the top-level subsystem down to (but not
    /// including) <paramref name="node"/>. Empty for a top-level node.</param>
    /// <param name="ancestorRouteBytes">Route id bytes for the same ancestors, parallel to
    /// <paramref name="ancestorDefines"/>.</param>
    private static SubsystemInfo BuildSubsystemTree(
        RouteNode node,
        List<string> ancestorDefines,
        List<byte> ancestorRouteBytes,
        StringBuilder output)
    {
        var selfChain = new List<string>(ancestorDefines) { node.Define };
        var selfRoute = new List<byte>(ancestorRouteBytes) { CSharpNaming.ParseHexByte(node.Id) };

        RouteNode? capsQueryChild = node.Routes.Values.FirstOrDefault(c => !c.IsRouter && c.Define == "CAPABILITIES_QUERY");
        bool hasCaps = capsQueryChild is not null;

        string className = string.Concat(ancestorDefines.Select(CSharpNaming.ToClassName)) + CSharpNaming.ToClassName(node.Define) + "Subsystem";
        // EnumGenerator unconditionally emits a top-level
        // `enum XapSubsystem` regardless of spec content. Every real XAP spec has a top-level
        // router literally named "XAP", so the naming algorithm above would otherwise collide
        // with that fixed enum name exactly once, for that one node. Disambiguate only that
        // specific, known, unavoidable collision -- the recursive algorithm itself stays generic.
        if (className == "XapSubsystem")
            className = "XapCoreSubsystem";
        string propertyName = CSharpNaming.ToClassName(node.Define);

        var childInfos = new List<SubsystemInfo>();
        foreach (RouteNode child in node.Routes.Values)
        {
            if (child.IsRouter)
                childInfos.Add(BuildSubsystemTree(child, selfChain, selfRoute, output));
        }

        var commands = node.Routes.Values
            .Where(c => !c.IsRouter && c.Define != "CAPABILITIES_QUERY" && c.Define != "SUBSYSTEM_QUERY")
            .ToList();

        output.AppendLine($"public sealed partial class {className}");
        output.AppendLine("{");
        output.AppendLine("    private readonly XapClient _client;");
        if (hasCaps)
            output.AppendLine("    private uint _capabilities;");
        output.AppendLine();

        output.AppendLine($"    internal {className}(XapClient client)");
        output.AppendLine("    {");
        output.AppendLine("        _client = client;");
        foreach (SubsystemInfo child in childInfos)
            output.AppendLine($"        {child.PropertyName} = new {child.ClassName}(client);");
        output.AppendLine("    }");
        output.AppendLine();

        foreach (SubsystemInfo child in childInfos)
            output.AppendLine($"    public {child.ClassName} {child.PropertyName} {{ get; }}");
        if (childInfos.Count > 0)
            output.AppendLine();

        if (hasCaps)
        {
            string bitPrefix = string.Concat(selfChain.Select(CSharpNaming.ToClassName));

            foreach (RouteNode? cmd in commands)
                output.AppendLine($"    public bool Has{CSharpNaming.ToClassName(cmd.Define)} => (_capabilities & XapConstants.{bitPrefix}{CSharpNaming.ToClassName(cmd.Define)}Bit) != 0;");

            // Nested-router children get a Has* property too, so recursive initialization (and
            // consumer code) can gate on them -- but ConstantsGenerator only emits bit
            // constants for LEAF (command) nodes, never for router nodes themselves (a router's
            // own id is a recursion point there, not a bit). There is therefore no
            // XapConstants.* name to reuse for a child ROUTER's bit; it is computed inline from
            // the child's own route id, which is the same "bit index == route id" rule
            // ConstantsGenerator applies to commands, just without a named constant.
            foreach (SubsystemInfo child in childInfos)
                output.AppendLine($"    public bool Has{child.PropertyName} => (_capabilities & (1u << {FormatHexByte(CSharpNaming.ParseHexByte(child.Node.Id))})) != 0;");

            if (commands.Count > 0 || childInfos.Count > 0)
                output.AppendLine();

            output.AppendLine("    internal async Task InitializeAsync(CancellationToken ct = default)");
            output.AppendLine("    {");
            output.AppendLine("        var token = _client.AllocateToken();");
            string capRoute = FormatByteArrayLiteral([.. selfRoute, CSharpNaming.ParseHexByte(capsQueryChild!.Id)]);
            output.AppendLine($"        var frame = _client.BuildRequest(token, {capRoute});");
            output.AppendLine("        _capabilities = await _client.ExecuteAsync<uint>(token, frame, XapReaders.U32, ct).ConfigureAwait(false);");
            foreach (SubsystemInfo child in childInfos)
                output.AppendLine($"        if (Has{child.PropertyName}) await {child.PropertyName}.InitializeAsync(ct).ConfigureAwait(false);");
            output.AppendLine("    }");
            output.AppendLine();
        }

        foreach (RouteNode? cmd in commands)
            AppendCommandMethod(output, cmd, selfChain, selfRoute, hasCaps);

        output.AppendLine("}");
        output.AppendLine();

        return new SubsystemInfo { ClassName = className, PropertyName = propertyName, HasCapabilities = hasCaps, Node = node };
    }

    // ---- Command method generation -----------------------------------------------------------

    private static void AppendCommandMethod(StringBuilder sb, RouteNode cmd, List<string> selfChain, List<byte> selfRoute, bool hasCaps)
    {
        bool isVoid = string.IsNullOrEmpty(cmd.ReturnType);
        string methodName = CSharpNaming.ToMethodName(cmd.Define, returnsData: !isVoid);
        string routeLabel = string.Join(".", selfChain.Select(CSharpNaming.ToClassName)) + "." + CSharpNaming.ToClassName(cmd.Define);
        string routeBytesLiteral = FormatByteArrayLiteral([.. selfRoute, CSharpNaming.ParseHexByte(cmd.Id)]);

        (string? returnCs, string? readerExpr) = isVoid ? ("", "") : ResolveReader(cmd, selfChain);

        string? requestParamType = null;
        bool requestIsStruct = cmd.RequestType == "struct";
        if (!string.IsNullOrEmpty(cmd.RequestType))
        {
            requestParamType = requestIsStruct
                ? RequestStructName(cmd, selfChain)
                : PrimitiveCsType(cmd.RequestType);
        }

        string paramList = requestParamType is null
            ? "CancellationToken ct = default"
            : $"{requestParamType} request, CancellationToken ct = default";

        sb.AppendLine($"    public async Task{(isVoid ? "" : $"<{returnCs}>")} {methodName}({paramList})");
        sb.AppendLine("    {");
        if (hasCaps)
        {
            sb.AppendLine($"        if (!Has{CSharpNaming.ToClassName(cmd.Define)})");
            sb.AppendLine($"            throw new XapRouteUnavailableException(\"{routeLabel}\");");
        }
        if (cmd.Permissions == "secure")
        {
            sb.AppendLine("        if (!_client.SecureUnlocked)");
            sb.AppendLine("            throw XapSecureFailureException.PreSendGuard();");
        }
        sb.AppendLine();
        sb.AppendLine("        var token = _client.AllocateToken();");

        if (requestParamType is not null)
        {
            if (requestIsStruct)
            {
                sb.AppendLine($"        var payload = new byte[{requestParamType}.SerializedSize];");
                sb.AppendLine("        request.WriteTo(payload);");
            }
            else
            {
                AppendPrimitiveRequestPayload(sb, cmd.RequestType, "request");
            }
            sb.AppendLine($"        var frame = _client.BuildRequest(token, {routeBytesLiteral}, payload);");
        }
        else
        {
            sb.AppendLine($"        var frame = _client.BuildRequest(token, {routeBytesLiteral});");
        }

        if (isVoid)
        {
            sb.AppendLine("        await _client.ExecuteAsync(token, frame, ct).ConfigureAwait(false);");
        }
        else if (cmd.Define == "GET_SECURE_STATUS")
        {
            sb.AppendLine("        _client.WatchSecureStatusResponse(token);");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            return await _client.ExecuteAsync<{returnCs}>(token, frame, {readerExpr}, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine("        finally");
            sb.AppendLine("        {");
            sb.AppendLine("            _client.UnwatchSecureStatusResponse(token);");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine($"        return await _client.ExecuteAsync<{returnCs}>(token, frame, {readerExpr}, ct).ConfigureAwait(false);");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Picks the C# return type and a matching <c>XapReader&lt;T&gt;</c>-compatible expression
    /// for a command's <c>return_type</c>. <c>return_purpose == "bcd-version"</c> overrides an
    /// otherwise-plain "u32" to decode via the generated XapVersion codec instead of
    /// XapReaders.U32 -- this is exactly VERSION_QUERY's real shape.
    /// </summary>
    private static (string CsType, string Reader) ResolveReader(RouteNode cmd, List<string> selfChain)
    {
        if (cmd.ReturnType == "struct")
        {
            string name = ReturnStructName(cmd, selfChain);
            return (name, $"{name}.ReadFrom");
        }

        if (cmd.ReturnType == "u32" && cmd.ReturnPurpose == "bcd-version")
            return ("XapVersion", "XapVersion.ReadFrom");

        if (cmd.ReturnType == "string")
            return ("string", "XapReaders.String");

        int bracket = cmd.ReturnType.IndexOf('[');
        if (bracket >= 0)
        {
            string elementType = cmd.ReturnType.Substring(0, bracket);
            string lengthStr = cmd.ReturnType.Substring(bracket + 1, cmd.ReturnType.Length - bracket - 2);

            if (elementType == "u8")
                return ("byte[]", "XapReaders.Bytes");

            (string? elemCs, string? readerMethod) = elementType switch
            {
                "u16" => ("ushort", "U16Array"),
                "u32" => ("uint", "U32Array"),
                "u64" => ("ulong", "U64Array"),
                _ => throw new InvalidOperationException($"Unsupported array element type in return_type '{cmd.ReturnType}'."),
            };
            return ($"{elemCs}[]", $"static s => XapReaders.{readerMethod}(s, {lengthStr})");
        }

        return cmd.ReturnType switch
        {
            "u8" => ("byte", "XapReaders.U8"),
            "u16" => ("ushort", "XapReaders.U16"),
            "u32" => ("uint", "XapReaders.U32"),
            "u64" => ("ulong", "XapReaders.U64"),
            _ => throw new InvalidOperationException($"Unsupported return_type '{cmd.ReturnType}'."),
        };
    }

    /// <summary>
    /// Struct type names must match TypeGenerator's own naming exactly -- a direct child of a
    /// TOP-LEVEL subsystem gets no prefix, while anything
    /// nested two-plus levels deep is prefixed with the immediate ancestor chain BELOW the
    /// top-level subsystem (selfChain minus its own first/top-level element).
    /// </summary>
    private static string ReturnStructName(RouteNode cmd, List<string> selfChain)
        => string.Concat(selfChain.Skip(1).Select(CSharpNaming.ToClassName)) + CSharpNaming.ToClassName(cmd.Define);

    private static string RequestStructName(RouteNode cmd, List<string> selfChain)
        => string.Concat(selfChain.Skip(1).Select(CSharpNaming.ToClassName)) + CSharpNaming.ToClassName(cmd.Define) + "Request";

    private static string PrimitiveCsType(string type) => type switch
    {
        "u8" => "byte",
        "u16" => "ushort",
        "u32" => "uint",
        "u64" => "ulong",
        _ => throw new InvalidOperationException($"Unsupported primitive request_type '{type}'."),
    };

    /// <summary>
    /// Emits `var payload = new byte[width]; <write call>;` for a primitive (non-struct) request
    /// type, little-endian. Mirrors the struct-request case's two-statement shape (allocate then
    /// fill) rather than building one big array-initializer expression.
    /// </summary>
    private static void AppendPrimitiveRequestPayload(StringBuilder sb, string type, string varName)
    {
        (int width, string? writeStmt) = type switch
        {
            "u8" => (1, $"payload[0] = {varName};"),
            "u16" => (2, $"BinaryPrimitives.WriteUInt16LittleEndian(payload, {varName});"),
            "u32" => (4, $"BinaryPrimitives.WriteUInt32LittleEndian(payload, {varName});"),
            "u64" => (8, $"BinaryPrimitives.WriteUInt64LittleEndian(payload, {varName});"),
            _ => throw new InvalidOperationException($"Unsupported primitive request_type '{type}'."),
        };

        sb.AppendLine($"        var payload = new byte[{width}];");
        sb.AppendLine($"        {writeStmt}");
    }

    // ---- Byte/hex helpers -------------------------------------------------------------------

    private static string FormatHexByte(byte b) => "0x" + b.ToString("X2", CultureInfo.InvariantCulture);

    private static string FormatByteArrayLiteral(List<byte> bytes)
        => "new byte[] { " + string.Join(", ", bytes.Select(FormatHexByte)) + " }";
}
