// Copyright 2026 QMK Collaborators
// SPDX-License-Identifier: MIT

using System.Text;
using Xap.SourceGenerator.Helpers;
using Xap.SourceGenerator.Models;

namespace Xap.SourceGenerator.Generators;

/// <summary>
/// Emits <c>Xap.Constants.g.cs</c>: a <c>static class XapConstants</c> holding one
/// <c>Route&lt;Subsystem&gt;</c> byte constant per top-level subsystem, plus one
/// <c>&lt;...&gt;Bit</c> uint constant per command (non-router) node anywhere in the tree.
/// </summary>
internal static class ConstantsGenerator
{
    public static string GenerateRouteIds(Dictionary<string, RouteNode> routes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Xap;");
        sb.AppendLine();
        sb.AppendLine("public static class XapConstants");
        sb.AppendLine("{");

        foreach (RouteNode node in routes.Values)
            sb.AppendLine($"    public const byte Route{CSharpNaming.ToClassName(node.Define)} = {node.Id};");

        var bits = new List<(string Name, string Id)>();
        CollectCapabilityBits(routes, [], bits);

        if (bits.Count > 0)
            sb.AppendLine();
        foreach ((string? name, string? id) in bits)
            sb.AppendLine($"    public const uint {name}Bit = 1u << {id};");

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Walks the route tree collecting one entry per command (non-router) node, keyed by ITS OWN
    /// hex id within its immediate parent's routes dictionary -- never a positional/ordinal count
    /// (the real spec's AUDIO subsystem, for instance, has routes {0x01, 0x03, 0x04, 0x05} with no
    /// 0x02, so a naive "index within parent" count would diverge from the real id). Names use the
    /// same full-ancestor-chain scheme as EnumGenerator.CollectRouteEnums, since the real
    /// spec reuses command defines like GET_CONFIG/SET_CONFIG across LIGHTING's nested
    /// BACKLIGHT/RGBLIGHT/RGB_MATRIX routers -- an unqualified or immediate-parent-only name would
    /// collide.
    /// </summary>
    private static void CollectCapabilityBits(
        Dictionary<string, RouteNode> routes,
        List<string> ancestorChain,
        List<(string Name, string Id)> output)
    {
        foreach (RouteNode node in routes.Values)
        {
            if (node.IsRouter)
            {
                var childChain = new List<string>(ancestorChain) { node.Define };
                CollectCapabilityBits(node.Routes, childChain, output);
                continue;
            }

            string prefix = string.Concat(ancestorChain.Select(CSharpNaming.ToClassName));
            output.Add((prefix + CSharpNaming.ToClassName(node.Define), node.Id));
        }
    }
}
