// Copyright 2026 QMK Collaborators
// SPDX-License-Identifier: MIT

using System.Text;
using Xap.SourceGenerator.Helpers;
using Xap.SourceGenerator.Models;

namespace Xap.SourceGenerator.Generators;

/// <summary>
/// Emits <c>Xap.Subsystems.g.cs</c>: a top-level <c>XapSubsystem</c> enum (one member per
/// top-level route) plus one <c>&lt;Name&gt;Route</c> enum per router node in the spec -- both
/// top-level subsystems and nested routers -- with one member per DIRECT non-router child.
/// </summary>
internal static class EnumGenerator
{
    // ResponseFlags is a hand-written [Flags] enum in Xap.Core (see
    // src/Xap.Core/ResponseFlags.cs). Generating a duplicate here would collide with it, so
    // this is a deliberate no-op -- response-flag *bit names* surface via ConstantsGenerator instead.
    public static string GenerateResponseFlags()
        => "// no generated response-flag enum -- see Xap.Core.ResponseFlags";

    public static string GenerateSubsystemEnums(Dictionary<string, RouteNode> routes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Xap;");
        sb.AppendLine();

        AppendSubsystemEnum(sb, routes);

        var routeEnums = new List<(string Name, List<(string Member, byte Value)> Members)>();
        CollectRouteEnums(routes, [], routeEnums);

        foreach ((string? name, List<(string Member, byte Value)>? members) in routeEnums)
            AppendRouteEnum(sb, name, members);

        return sb.ToString();
    }

    // ---- XapSubsystem (top-level routes only) ---------------------------------------------

    private static void AppendSubsystemEnum(StringBuilder sb, Dictionary<string, RouteNode> routes)
    {
        sb.AppendLine("public enum XapSubsystem : byte");
        sb.AppendLine("{");
        foreach (RouteNode node in routes.Values)
            sb.AppendLine($"    {CSharpNaming.ToClassName(node.Define)} = {CSharpNaming.ParseHexByte(node.Id)},");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---- Route enum discovery ---------------------------------------------------------------

    /// <summary>
    /// Walks the route tree, emitting one enum per router (top-level subsystem or nested).
    /// A top-level router's enum is named "&lt;Define&gt;Route" (ancestorChain is empty).
    /// A nested router folds every ancestor router's Define into its own name so reused defines
    /// (BACKLIGHT/RGBLIGHT/RGB_MATRIX all nest CAPABILITIES_QUERY/GET_CONFIG/etc. under LIGHTING)
    /// stay unique -- e.g. "LightingBacklightRoute", "LightingRgblightRoute". Unlike
    /// TypeGenerator.CollectStructs (which prefixes leaf struct names with only the immediate
    /// parent router),
    /// this must include the FULL ancestry because the enum is named after the router itself.
    /// </summary>
    private static void CollectRouteEnums(
        Dictionary<string, RouteNode> routes,
        List<string> ancestorChain,
        List<(string Name, List<(string Member, byte Value)> Members)> output)
    {
        foreach (RouteNode node in routes.Values)
        {
            if (!node.IsRouter)
                continue;

            string prefix = string.Concat(ancestorChain.Select(CSharpNaming.ToClassName));
            string enumName = prefix + CSharpNaming.ToClassName(node.Define) + "Route";

            var members = node.Routes.Values
                .Where(child => !child.IsRouter)
                .Select(child => (CSharpNaming.ToClassName(child.Define), CSharpNaming.ParseHexByte(child.Id)))
                .ToList();

            output.Add((enumName, members));

            var childChain = new List<string>(ancestorChain) { node.Define };
            CollectRouteEnums(node.Routes, childChain, output);
        }
    }

    private static void AppendRouteEnum(StringBuilder sb, string name, List<(string Member, byte Value)> members)
    {
        sb.AppendLine($"public enum {name} : byte");
        sb.AppendLine("{");
        foreach ((string? member, byte value) in members)
            sb.AppendLine($"    {member} = {value},");
        sb.AppendLine("}");
        sb.AppendLine();
    }

}
