// Copyright 2026 QMK Collaborators
// SPDX-License-Identifier: MIT

using System.Globalization;
using System.Text;
using Xap.SourceGenerator.Helpers;
using Xap.SourceGenerator.Models;

namespace Xap.SourceGenerator.Generators;

/// <summary>
/// Emits <c>Xap.Types.g.cs</c>: the always-present <c>XapVersion</c> BCD codec, plus one
/// <c>readonly struct</c> per route struct definition in the spec (both
/// <see cref="RouteNode.ReturnStructMembers"/> and <see cref="RouteNode.RequestStructMembers"/>).
/// All multi-byte fields are decoded/encoded little-endian, field by field -- never via
/// <c>MemoryMarshal</c>/blitting, since that would be endian-unsafe and struct-layout-fragile.
/// </summary>
internal static class TypeGenerator
{
    public static string GenerateTypes(XapSpecModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Buffers.Binary;");
        sb.AppendLine();
        sb.AppendLine("namespace Xap;");
        sb.AppendLine();

        AppendXapVersion(sb);

        var structs = new List<(string Name, List<StructMember> Members)>();
        CollectStructs(model.Routes, ancestorChain: null, structs);

        foreach ((string? name, List<StructMember>? members) in structs)
            AppendStruct(sb, name, members);

        return sb.ToString();
    }

    // ---- Struct discovery -------------------------------------------------------------

    /// <summary>
    /// Walks the route tree collecting one entry per declared struct. Struct names are derived
    /// from the owning route's Define, PascalCased. A direct child of a top-level subsystem
    /// (e.g. QMK / BOARD_IDENTIFIERS, KEYMAP / GET_KEYMAP_KEYCODE) gets no prefix. A route nested
    /// two or more levels deep (e.g. LIGHTING -> BACKLIGHT -> GET_CONFIG) is prefixed with its
    /// immediate parent router's Define, since the real spec reuses defines like GET_CONFIG /
    /// SET_CONFIG across multiple nested routers (Backlight, Rgblight, RgbMatrix) and an
    /// unqualified name would collide.
    /// </summary>
    private static void CollectStructs(
        Dictionary<string, RouteNode> routes,
        List<string>? ancestorChain,
        List<(string Name, List<StructMember> Members)> output)
    {
        foreach (RouteNode node in routes.Values)
        {
            if (node.IsRouter)
            {
                // Top-level subsystems (ancestorChain == null) don't contribute their own Define
                // as a prefix -- only routers nested beneath a subsystem do.
                List<string> childChain = ancestorChain is null
                    ? []
                    : [.. ancestorChain, node.Define];

                CollectStructs(node.Routes, childChain, output);
                continue;
            }

            string prefix = ancestorChain is null ? "" : string.Concat(ancestorChain.Select(CSharpNaming.ToClassName));

            if (node.ReturnType == "struct" && node.ReturnStructMembers.Count > 0)
                output.Add((prefix + CSharpNaming.ToClassName(node.Define), node.ReturnStructMembers));

            if (node.RequestType == "struct" && node.RequestStructMembers.Count > 0)
                output.Add((prefix + CSharpNaming.ToClassName(node.Define) + "Request", node.RequestStructMembers));
        }
    }

    // ---- XapVersion (always emitted) --------------------------------------------------

    private static void AppendXapVersion(StringBuilder sb)
    {
        sb.AppendLine("""
            public readonly struct XapVersion
            {
                public readonly byte Major;
                public readonly byte Minor;
                public readonly ushort Patch;

                public XapVersion(byte major, byte minor, ushort patch)
                {
                    Major = major;
                    Minor = minor;
                    Patch = patch;
                }

                private static byte FromBcd8(byte v) => (byte)(((v >> 4) * 10) + (v & 0x0F));

                private static ushort FromBcd16(ushort v)
                    => (ushort)((((v >> 12) & 0xF) * 1000) + (((v >> 8) & 0xF) * 100)
                              + (((v >> 4) & 0xF) * 10) + (v & 0xF));

                private static byte ToBcd8(byte v) => (byte)(((v / 10) << 4) | (v % 10));

                private static ushort ToBcd16(ushort v)
                    => (ushort)((((v / 1000) % 10) << 12) | (((v / 100) % 10) << 8)
                              | (((v / 10) % 10) << 4) | (v % 10));

                /// <summary>
                /// Decodes a BCD-encoded XAP version word (wire format: bits 31-24 = major BCD,
                /// bits 23-16 = minor BCD, bits 15-0 = patch BCD as a little-endian u16, e.g.
                /// 3.2.115 == 0x03020115). This operates on the already-assembled u32 value, not
                /// on raw wire bytes -- use ReadFrom for that.
                /// </summary>
                public static XapVersion FromBcd(uint bcd)
                {
                    byte majorBcd = (byte)((bcd >> 24) & 0xFF);
                    byte minorBcd = (byte)((bcd >> 16) & 0xFF);
                    ushort patchBcd = (ushort)(bcd & 0xFFFF);
                    return new XapVersion(FromBcd8(majorBcd), FromBcd8(minorBcd), FromBcd16(patchBcd));
                }

                public uint ToBcd()
                {
                    uint major = ToBcd8(Major);
                    uint minor = ToBcd8(Minor);
                    uint patch = ToBcd16(Patch);
                    return (major << 24) | (minor << 16) | patch;
                }

                public static int SerializedSize => 4;

                // src = {PatchLow, PatchHigh, Minor, Major}, all BCD, little-endian.
                public static XapVersion ReadFrom(ReadOnlySpan<byte> src)
                {
                    if (src.Length < SerializedSize)
                        throw new XapParseException($"XapVersion needs {SerializedSize} bytes, got {src.Length}.");

                    ushort patchBcd = (ushort)(src[0] | (src[1] << 8));
                    return new XapVersion(FromBcd8(src[3]), FromBcd8(src[2]), FromBcd16(patchBcd));
                }

                public void WriteTo(Span<byte> dest)
                {
                    if (dest.Length < SerializedSize)
                        throw new XapParseException($"XapVersion needs {SerializedSize} bytes, got {dest.Length}.");

                    ushort patchBcd = ToBcd16(Patch);
                    dest[0] = (byte)(patchBcd & 0xFF);
                    dest[1] = (byte)((patchBcd >> 8) & 0xFF);
                    dest[2] = ToBcd8(Minor);
                    dest[3] = ToBcd8(Major);
                }

                public override string ToString() => $"{Major}.{Minor}.{Patch}";
            }
            """);
        sb.AppendLine();
    }

    // ---- Per-spec structs ---------------------------------------------------------------

    private sealed class FieldInfo
    {
        public string Name = "";
        public string ElementCsType = "";
        public bool IsArray;
        public int ElementWidth;   // bytes per element (1, 2, 4, 8)
        public int ArrayLength = 1; // 1 for scalars
        public int Offset;

        public string CsType => IsArray ? ElementCsType + "[]" : ElementCsType;
        public int Size => ElementWidth * ArrayLength;
    }

    private static void AppendStruct(StringBuilder sb, string structName, List<StructMember> members)
    {
        var fields = new List<FieldInfo>();
        int offset = 0;
        foreach (StructMember member in members)
        {
            FieldInfo field = ParseField(member, offset);
            fields.Add(field);
            offset += field.Size;
        }

        int totalSize = offset;

        sb.AppendLine($"public readonly struct {structName}");
        sb.AppendLine("{");

        foreach (FieldInfo field in fields)
            sb.AppendLine($"    public readonly {field.CsType} {field.Name};");

        sb.AppendLine();
        sb.AppendLine($"    public {structName}({string.Join(", ", fields.Select(f => $"{f.CsType} {ParamName(f.Name)}"))})");
        sb.AppendLine("    {");
        foreach (FieldInfo field in fields)
            sb.AppendLine($"        {field.Name} = {ParamName(field.Name)};");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine($"    public static int SerializedSize => {totalSize};");

        sb.AppendLine();
        sb.AppendLine($"    public static {structName} ReadFrom(ReadOnlySpan<byte> src)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (src.Length < SerializedSize)");
        sb.AppendLine($"            throw new XapParseException($\"{structName} needs {{SerializedSize}} bytes, got {{src.Length}}.\");");
        sb.AppendLine();
        foreach (FieldInfo field in fields)
            AppendFieldRead(sb, field);
        sb.AppendLine();
        sb.AppendLine($"        return new {structName}({string.Join(", ", fields.Select(f => ParamName(f.Name)))});");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    public void WriteTo(Span<byte> dest)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (dest.Length < SerializedSize)");
        sb.AppendLine($"            throw new XapParseException($\"{structName} needs {{SerializedSize}} bytes, got {{dest.Length}}.\");");
        foreach (FieldInfo field in fields)
            AppendFieldWrite(sb, field);
        sb.AppendLine("    }");

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static FieldInfo ParseField(StructMember member, int offset)
    {
        string type = member.Type;
        int bracketIdx = type.IndexOf('[');

        if (bracketIdx >= 0)
        {
            string elementType = type.Substring(0, bracketIdx);
            string lengthStr = type.Substring(bracketIdx + 1, type.Length - bracketIdx - 2);
            int length = int.Parse(lengthStr, CultureInfo.InvariantCulture);
            (string? elemCs, int elemWidth) = PrimitiveInfo(elementType);

            return new FieldInfo
            {
                Name = CSharpNaming.ToClassName(member.Name),
                IsArray = true,
                ElementCsType = elemCs,
                ElementWidth = elemWidth,
                ArrayLength = length,
                Offset = offset,
            };
        }

        (string? cs, int width) = PrimitiveInfo(type);
        return new FieldInfo
        {
            Name = CSharpNaming.ToClassName(member.Name),
            IsArray = false,
            ElementCsType = cs,
            ElementWidth = width,
            ArrayLength = 1,
            Offset = offset,
        };
    }

    private static (string CsType, int Width) PrimitiveInfo(string type) => type switch
    {
        "u8" => ("byte", 1),
        "u16" => ("ushort", 2),
        "u32" => ("uint", 4),
        "u64" => ("ulong", 8),
        "bool" => ("bool", 1),
        _ => throw new InvalidOperationException($"Unsupported XAP struct member type: '{type}'."),
    };

    private static void AppendFieldRead(StringBuilder sb, FieldInfo field)
    {
        string name = ParamName(field.Name);

        if (!field.IsArray)
        {
            sb.AppendLine($"        {field.CsType} {name} = {ScalarReadExpr(field.ElementCsType, "src", field.Offset.ToString(CultureInfo.InvariantCulture))};");
            return;
        }

        sb.AppendLine($"        var {name} = new {field.ElementCsType}[{field.ArrayLength}];");
        sb.AppendLine($"        for (int i = 0; i < {field.ArrayLength}; i++)");
        sb.AppendLine("        {");
        sb.AppendLine($"            int o = {field.Offset} + i * {field.ElementWidth};");
        sb.AppendLine($"            {name}[i] = {ScalarReadExpr(field.ElementCsType, "src", "o")};");
        sb.AppendLine("        }");
    }

    private static string ScalarReadExpr(string elementCsType, string span, string offsetExpr) => elementCsType switch
    {
        "byte" => $"{span}[{offsetExpr}]",
        "bool" => $"{span}[{offsetExpr}] != 0",
        "ushort" => $"BinaryPrimitives.ReadUInt16LittleEndian({span}.Slice({offsetExpr}, 2))",
        "uint" => $"BinaryPrimitives.ReadUInt32LittleEndian({span}.Slice({offsetExpr}, 4))",
        "ulong" => $"BinaryPrimitives.ReadUInt64LittleEndian({span}.Slice({offsetExpr}, 8))",
        _ => throw new InvalidOperationException($"Unsupported element type: '{elementCsType}'."),
    };

    private static void AppendFieldWrite(StringBuilder sb, FieldInfo field)
    {
        string name = field.Name;

        if (!field.IsArray)
        {
            AppendScalarWriteStmts(sb, field.ElementCsType, "dest", field.Offset.ToString(CultureInfo.InvariantCulture), name, indent: "        ");
            return;
        }

        sb.AppendLine($"        for (int i = 0; i < {field.ArrayLength}; i++)");
        sb.AppendLine("        {");
        sb.AppendLine($"            int o = {field.Offset} + i * {field.ElementWidth};");
        AppendScalarWriteStmts(sb, field.ElementCsType, "dest", "o", $"{name}[i]", indent: "            ");
        sb.AppendLine("        }");
    }

    private static void AppendScalarWriteStmts(StringBuilder sb, string elementCsType, string span, string offsetExpr, string valueExpr, string indent)
    {
        switch (elementCsType)
        {
            case "byte":
                sb.AppendLine($"{indent}{span}[{offsetExpr}] = {valueExpr};");
                break;
            case "bool":
                sb.AppendLine($"{indent}{span}[{offsetExpr}] = (byte)({valueExpr} ? 1 : 0);");
                break;
            case "ushort":
                sb.AppendLine($"{indent}BinaryPrimitives.WriteUInt16LittleEndian({span}.Slice({offsetExpr}, 2), {valueExpr});");
                break;
            case "uint":
                sb.AppendLine($"{indent}BinaryPrimitives.WriteUInt32LittleEndian({span}.Slice({offsetExpr}, 4), {valueExpr});");
                break;
            case "ulong":
                sb.AppendLine($"{indent}BinaryPrimitives.WriteUInt64LittleEndian({span}.Slice({offsetExpr}, 8), {valueExpr});");
                break;
            default:
                throw new InvalidOperationException($"Unsupported element type: '{elementCsType}'.");
        }
    }

    // ---- Naming -------------------------------------------------------------------------

    private static string ParamName(string pascalFieldName)
        => pascalFieldName.Length == 0
            ? pascalFieldName
            : char.ToLowerInvariant(pascalFieldName[0]) + pascalFieldName.Substring(1);
}
